# Generated by Django 4.2 on 2023-05-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LV_info", "0004_alter_lv_database_current_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lv_database",
            name="current_state",
            field=models.SmallIntegerField(
                choices=[
                    (1, "待定状态"),
                    (2, "转染中"),
                    (3, "24小时拍照"),
                    (4, "收毒中"),
                    (5, "纯化中"),
                    (6, "已送检"),
                ],
                default=1,
                verbose_name="当前状态",
            ),
        ),
        migrations.AlterField(
            model_name="lv_database",
            name="hours24_state",
            field=models.SmallIntegerField(
                choices=[(1, "待定状态"), (2, "正常状态"), (3, "荧光污染"), (4, "荧光效率低")],
                default=1,
                verbose_name="24小时订单状态",
            ),
        ),
    ]
