# Generated by Django 4.2 on 2023-05-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LV_info", "0006_alter_lv_database_titer_requirement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lv_database",
            name="dispatch",
            field=models.CharField(max_length=20, verbose_name="分装量"),
        ),
    ]
