# Generated by Django 4.2 on 2023-05-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LV_info", "0007_alter_lv_database_dispatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="lv_database",
            name="Remarks",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="备注"
            ),
        ),
    ]
