# Generated by Django 4.2 on 2023-05-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LV_info", "0008_lv_database_remarks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lv_database", old_name="vertor_name", new_name="vector_name",
        ),
        migrations.RenameField(
            model_name="lv_database", old_name="vertor_type", new_name="vector_type",
        ),
    ]
