# Generated by Django 4.2 on 2023-05-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LV_info", "0009_rename_vertor_name_lv_database_vector_name_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="lv_database", table="lv_database",),
    ]
