# Generated by Django 4.2 on 2023-05-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LV_info", "0010_alter_lv_database_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lv_database",
            name="vector_type",
            field=models.SmallIntegerField(
                choices=[(1, "一代载体"), (2, "二代载体"), (3, "三代载体")],
                default=3,
                verbose_name="载体类型",
            ),
        ),
    ]
