# Generated by Django 4.2 on 2023-05-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LV_info", "0013_alter_lv_database_vector_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="lv_database", name="order_date",),
    ]
