# Generated by Django 4.2 on 2023-05-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LV_info", "0014_remove_lv_database_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="lv_database",
            name="order_date",
            field=models.DateTimeField(default="2022-01-01", verbose_name="下单日期"),
        ),
    ]
