# Generated by Django 4.2 on 2023-05-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LV_info", "0015_lv_database_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lv_database",
            name="order_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="下单日期"),
        ),
    ]
