# Generated by Django 4.2 on 2023-05-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TechSupport_database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.CharField(max_length=20, verbose_name="订单号")),
                (
                    "order_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "过表达慢病毒"),
                            (2, "干扰慢病毒"),
                            (3, "blank"),
                            (4, "sgRNA-Cas9慢病毒"),
                            (5, "shRNA慢病毒"),
                        ],
                        verbose_name="订单类型",
                    ),
                ),
                ("gene_name", models.CharField(max_length=80, verbose_name="基因名称")),
                ("gene_num", models.IntegerField(verbose_name="基因大小")),
                ("vector_name", models.CharField(max_length=100, verbose_name="载体名称")),
                ("virus_volume", models.CharField(max_length=20, verbose_name="病毒量")),
                (
                    "titer_requirement",
                    models.CharField(max_length=20, verbose_name="滴度要求"),
                ),
                (
                    "order_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="订单日期"),
                ),
                (
                    "specify_completion_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="规定完成日期"),
                ),
                (
                    "shipping_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="发货日期"),
                ),
                (
                    "customer_unit",
                    models.CharField(max_length=200, verbose_name="客户单位"),
                ),
                ("sales_manager", models.CharField(max_length=10, verbose_name="销售经理")),
                (
                    "entered_by",
                    models.SmallIntegerField(
                        choices=[(1, "李雨晴"), (2, "周华香")], verbose_name="录入人"
                    ),
                ),
                ("dispatch", models.CharField(max_length=20, verbose_name="分装量")),
                ("pipe_num", models.IntegerField(verbose_name="总支数")),
                (
                    "titer_result",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="滴度结果"
                    ),
                ),
                (
                    "iqc_result",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="质检结果"
                    ),
                ),
                (
                    "shipping_Remarks",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="发货备注"
                    ),
                ),
                (
                    "Remarks",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="备注"
                    ),
                ),
            ],
        ),
    ]
