# Generated by Django 4.2 on 2023-05-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TechSupport_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="techsupport_database", options={"verbose_name": "慢病毒数据库"},
        ),
    ]
