# Generated by Django 4.2 on 2023-05-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TechSupport_info", "0002_alter_techsupport_database_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="techsupport_database", options={},),
        migrations.AlterModelTable(
            name="techsupport_database", table="tech_support_database",
        ),
    ]
