# Generated by Django 4.2 on 2023-05-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OQC_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="oqc_database", table="oqc_database",),
    ]
