# Generated by Django 4.2 on 2023-05-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OQC_info", "0002_alter_oqc_database_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oqc_database",
            name="shopping_Remarks",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="发货备注"
            ),
        ),
    ]
