# Generated by Django 4.2 on 2023-05-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OQC_info", "0004_alter_oqc_database_titer_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="oqc_database",
            name="check_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审核日期"),
        ),
        migrations.AddField(
            model_name="oqc_database",
            name="checker",
            field=models.CharField(
                choices=[("吴亚楠", "吴亚楠"), ("冯邦水", "冯邦水"), ("陈丛水", "陈丛水")],
                default="吴亚楠",
                max_length=10,
                verbose_name="审核人",
            ),
        ),
        migrations.AddField(
            model_name="oqc_database",
            name="dispatch",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="分装量"
            ),
        ),
        migrations.AddField(
            model_name="oqc_database",
            name="gene_name",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="基因名称"
            ),
        ),
        migrations.AddField(
            model_name="oqc_database",
            name="lv_DeliveryDate",
            field=models.DateTimeField(blank=True, null=True, verbose_name="送检日期"),
        ),
        migrations.AddField(
            model_name="oqc_database",
            name="pipe_num",
            field=models.IntegerField(blank=True, null=True, verbose_name="总支数"),
        ),
        migrations.AddField(
            model_name="oqc_database",
            name="report_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="报告日期"),
        ),
        migrations.AddField(
            model_name="oqc_database",
            name="reporter",
            field=models.CharField(
                choices=[("吴亚楠", "吴亚楠"), ("冯邦水", "冯邦水"), ("陈丛水", "陈丛水")],
                default="吴亚楠",
                max_length=10,
                verbose_name="报告人",
            ),
        ),
        migrations.AddField(
            model_name="oqc_database",
            name="vector_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="载体名称"
            ),
        ),
        migrations.AddField(
            model_name="oqc_database",
            name="vector_type",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="载体类型"
            ),
        ),
    ]
