# Generated by Django 4.2 on 2023-05-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IQC_info", "0002_iqc_database_remarks_iqc_database_infection_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="iqc_database", old_name="vertor_name", new_name="vector_name",
        ),
    ]
