# Generated by Django 4.2 on 2023-05-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IQC_info", "0003_rename_vertor_name_iqc_database_vector_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="iqc_database",
            name="infected_people",
            field=models.SmallIntegerField(
                choices=[(1, "吴亚楠"), (2, "冯邦水"), (3, "王梦月"), (4, "李井"), (5, "陈丛水")],
                default=1,
                verbose_name="感染人",
            ),
        ),
        migrations.AddField(
            model_name="iqc_database",
            name="puro_people",
            field=models.SmallIntegerField(
                choices=[(1, "吴亚楠"), (2, "冯邦水"), (3, "王梦月"), (4, "李井"), (5, "陈丛水")],
                default=1,
                verbose_name="加药人",
            ),
        ),
    ]
