# Generated by Django 4.2 on 2023-05-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IQC_info", "0004_iqc_database_infected_people_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="iqc_database", table="iqc_database",),
    ]
