# Generated by Django 4.2 on 2023-05-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IQC_info", "0005_alter_iqc_database_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iqc_database",
            name="infection_status",
            field=models.SmallIntegerField(
                choices=[
                    (1, "待定状态"),
                    (2, "已感染(ZsGreen)"),
                    (3, "已感染(Puro)"),
                    (4, "已感染6孔板"),
                    (5, "已感染24孔板"),
                    (6, "已收集细胞，提基因组"),
                    (7, "已加药，开始药筛"),
                    (8, "已提RNA并反转录"),
                    (9, "质检完成"),
                ],
                default=1,
                verbose_name="感染状态",
            ),
        ),
    ]
